spring:
  config:
    activate:
      on-profile: local

  kafka:
    bootstrap-servers: localhost:29092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

    streams:
      application-id: order
      state-store-cache-max-size: 0
      properties:
        default:
          deserialization:
            exception:
              handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler

  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:28017/order_db

logging:
  level:
    web: debug
    sql: debug